FREERTOS_REL_DIR := Lib/FreeRTOS

C_SOURCES_FREERTOS += $(FREERTOS_REL_DIR)/Source/croutine.c
C_SOURCES_FREERTOS += $(FREERTOS_REL_DIR)/Source/event_groups.c
C_SOURCES_FREERTOS += $(FREERTOS_REL_DIR)/Source/list.c
C_SOURCES_FREERTOS_GCC += $(FREERTOS_REL_DIR)/Source/portable/GCC/ARM_CM55_NTZ/non_secure/port.c
C_SOURCES_FREERTOS_GCC += $(FREERTOS_REL_DIR)/Source/portable/GCC/ARM_CM55_NTZ/non_secure/portasm.c
C_SOURCES_FREERTOS_IAR += $(FREERTOS_REL_DIR)/Source/portable/IAR/ARM_CM55_NTZ/non_secure/port.c
C_SOURCES_FREERTOS += $(FREERTOS_REL_DIR)/Source/queue.c
C_SOURCES_FREERTOS += $(FREERTOS_REL_DIR)/Source/tasks.c
C_SOURCES_FREERTOS += $(FREERTOS_REL_DIR)/Source/timers.c
C_SOURCES_FREERTOS += $(FREERTOS_REL_DIR)/Source/portable/MemMang/heap_4.c

ASM_SOURCES_FREERTOS_IAR += $(FREERTOS_REL_DIR)/Source/portable/IAR/ARM_CM55_NTZ/non_secure/portasm.s

C_INCLUDES_FREERTOS += -I$(FREERTOS_REL_DIR)/Source/include
C_INCLUDES_FREERTOS += -I$(FREERTOS_REL_DIR)/Source/portable/GCC/ARM_CM55_NTZ/non_secure

C_DEFS_FREERTOS += -DFEAT_FREERTOS

C_SOURCES += $(C_SOURCES_FREERTOS)
C_SOURCES_GCC += $(C_SOURCES_FREERTOS_GCC)
C_SOURCES_IAR += $(C_SOURCES_FREERTOS_IAR)
ASM_SOURCES_IAR += $(ASM_SOURCES_FREERTOS_IAR)
C_INCLUDES += $(C_INCLUDES_FREERTOS)
C_DEFS += $(C_DEFS_FREERTOS)
