################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ecloader.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_cipher.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_debug.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib_sw_operators.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_osal_freertos.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_rt_main.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_runtime.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_stai_internal.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_util.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_sw_float.c \
D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_sw_integer.c 

OBJS += \
./Lib/AI_Runtime/Npu/ll_aton/ecloader.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_cipher.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_debug.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib_sw_operators.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_osal_freertos.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_rt_main.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_runtime.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_stai_internal.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_util.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_sw_float.o \
./Lib/AI_Runtime/Npu/ll_aton/ll_sw_integer.o 

C_DEPS += \
./Lib/AI_Runtime/Npu/ll_aton/ecloader.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_cipher.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_debug.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib_sw_operators.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_osal_freertos.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_rt_main.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_runtime.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_stai_internal.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_aton_util.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_sw_float.d \
./Lib/AI_Runtime/Npu/ll_aton/ll_sw_integer.d 


# Each subdirectory must supply rules for building sources it contributes
Lib/AI_Runtime/Npu/ll_aton/ecloader.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ecloader.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_aton.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_aton_cipher.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_cipher.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_aton_debug.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_debug.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib_sw_operators.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib_sw_operators.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_aton_osal_freertos.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_osal_freertos.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_aton_rt_main.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_rt_main.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_aton_runtime.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_runtime.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_aton_stai_internal.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_stai_internal.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_aton_util.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_aton_util.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_sw_float.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_sw_float.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/AI_Runtime/Npu/ll_aton/ll_sw_integer.o: D:/HUU_UYEN/Software/1.STM32-N6/Code/uvc-ai-stm32/Lib/AI_Runtime/Npu/ll_aton/ll_sw_integer.c Lib/AI_Runtime/Npu/ll_aton/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Lib-2f-AI_Runtime-2f-Npu-2f-ll_aton

clean-Lib-2f-AI_Runtime-2f-Npu-2f-ll_aton:
	-$(RM) ./Lib/AI_Runtime/Npu/ll_aton/ecloader.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ecloader.d ./Lib/AI_Runtime/Npu/ll_aton/ecloader.o ./Lib/AI_Runtime/Npu/ll_aton/ecloader.su ./Lib/AI_Runtime/Npu/ll_aton/ll_aton.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_aton.d ./Lib/AI_Runtime/Npu/ll_aton/ll_aton.o ./Lib/AI_Runtime/Npu/ll_aton/ll_aton.su ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_cipher.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_cipher.d ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_cipher.o ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_cipher.su ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_debug.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_debug.d ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_debug.o ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_debug.su ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib.d ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib.o ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib.su ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib_sw_operators.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib_sw_operators.d ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib_sw_operators.o ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_lib_sw_operators.su ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_osal_freertos.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_osal_freertos.d ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_osal_freertos.o ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_osal_freertos.su ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_rt_main.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_rt_main.d ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_rt_main.o ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_rt_main.su ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_runtime.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_runtime.d ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_runtime.o ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_runtime.su ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_stai_internal.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_stai_internal.d ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_stai_internal.o ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_stai_internal.su ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_util.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_util.d ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_util.o ./Lib/AI_Runtime/Npu/ll_aton/ll_aton_util.su ./Lib/AI_Runtime/Npu/ll_aton/ll_sw_float.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_sw_float.d ./Lib/AI_Runtime/Npu/ll_aton/ll_sw_float.o ./Lib/AI_Runtime/Npu/ll_aton/ll_sw_float.su ./Lib/AI_Runtime/Npu/ll_aton/ll_sw_integer.cyclo ./Lib/AI_Runtime/Npu/ll_aton/ll_sw_integer.d ./Lib/AI_Runtime/Npu/ll_aton/ll_sw_integer.o ./Lib/AI_Runtime/Npu/ll_aton/ll_sw_integer.su

.PHONY: clean-Lib-2f-AI_Runtime-2f-Npu-2f-ll_aton

