################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Subway/x-cube-n6-ai-h264-usb-uvc-main/Lib/Camera_Middleware/sensors/imx335/imx335.c \
D:/Subway/x-cube-n6-ai-h264-usb-uvc-main/Lib/Camera_Middleware/sensors/imx335/imx335_reg.c 

OBJS += \
./Lib/Camera_Middleware/sensors/imx335/imx335.o \
./Lib/Camera_Middleware/sensors/imx335/imx335_reg.o 

C_DEPS += \
./Lib/Camera_Middleware/sensors/imx335/imx335.d \
./Lib/Camera_Middleware/sensors/imx335/imx335_reg.d 


# Each subdirectory must supply rules for building sources it contributes
Lib/Camera_Middleware/sensors/imx335/imx335.o: D:/Subway/x-cube-n6-ai-h264-usb-uvc-main/Lib/Camera_Middleware/sensors/imx335/imx335.c Lib/Camera_Middleware/sensors/imx335/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_IMX335_SENSOR -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/imx335 -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Lib/Camera_Middleware/sensors/imx335/imx335_reg.o: D:/Subway/x-cube-n6-ai-h264-usb-uvc-main/Lib/Camera_Middleware/sensors/imx335/imx335_reg.c Lib/Camera_Middleware/sensors/imx335/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m55 -std=gnu11 -g3 -DSTM32N657xx -DUSE_FULL_ASSERT -DUSE_FULL_LL_DRIVER -DVECT_TAB_SRAM -DUSE_IMX335_SENSOR -DUSE_VD66GY_SENSOR -DUSE_VD55G1_SENSOR -DUSE_VD1943_SENSOR -DTX_MAX_PARALLEL_NETWORKS=1 -DLL_ATON_PLATFORM=LL_ATON_PLAT_STM32N6 -DLL_ATON_OSAL=LL_ATON_OSAL_FREERTOS -DLL_ATON_RT_MODE=LL_ATON_RT_ASYNC -DLL_ATON_SW_FALLBACK -DLL_ATON_DBG_BUFFER_INFO_EXCLUDED=1 -DAPP_HAS_PARALLEL_NETWORKS=0 -DFEAT_FREERTOS -DUVC_LIB_USE_USBX -DUX_INCLUDE_USER_DEFINE_FILE -DUSBL_PACKET_PER_MICRO_FRAME=3 -DUX_STANDALONE -DUVCL_USBX_USE_FREERTOS -DUVC_LIB_USE_DMA -c -I../../Inc -I../../Model -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc -I../../STM32Cube_FW_N6/Drivers/STM32N6xx_HAL_Driver/Inc/Legacy -I../../STM32Cube_FW_N6/Drivers/CMSIS/Device/ST/STM32N6xx/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/Include -I../../STM32Cube_FW_N6/Drivers/CMSIS/DSP/Include -I../../STM32Cube_FW_N6/Drivers/BSP/Components/Common -I../../STM32Cube_FW_N6/Drivers/BSP/STM32N6570-DK -I../../STM32Cube_FW_N6/Utilities/Fonts -I../../STM32Cube_FW_N6/Drivers/BSP/Components/aps256xx -I../../Lib/AI_Runtime/Inc -I../../Lib/AI_Runtime/Npu/ll_aton -I../../Lib/AI_Runtime/Npu/Devices/STM32N6xx -I../../Lib/lib_vision_models_pp/lib_vision_models_pp/Inc -I../../Lib/ai-postprocessing-wrapper -I../../Lib/Camera_Middleware -I../../Lib/Camera_Middleware/sensors -I../../Lib/Camera_Middleware/sensors/imx335 -I../../Lib/Camera_Middleware/sensors/vd55g1 -I../../Lib/Camera_Middleware/sensors/vd6g -I../../Lib/Camera_Middleware/sensors/vd1943 -I../../Lib/Camera_Middleware/ISP_Library/isp/Inc -I../../Lib/Camera_Middleware/ISP_Library/evision/Inc -I../../Lib/FreeRTOS/Source/include -I../../Lib/FreeRTOS/Source/portable/GCC/ARM_CM55_NTZ/non_secure -I../../STM32Cube_FW_N6/Middlewares/ST/VideoEncoder_EWL -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/inc -I../../STM32Cube_FW_N6/Middlewares/Third_Party/VideoEncoder/source/common -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/core/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/ports/generic/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_device_classes/inc -I../../STM32Cube_FW_N6/Middlewares/ST/usbx/common/usbx_stm32_device_controllers -I../../Lib/uvcl/Inc/usbx -I../../Lib/uvcl/Src/usbx -I../../Lib/uvcl/Inc -I../../Lib/uvcl/Src -Os -ffunction-sections -fdata-sections -Wall -std=c11 -fstack-usage -fcyclomatic-complexity -mcmse -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Lib-2f-Camera_Middleware-2f-sensors-2f-imx335

clean-Lib-2f-Camera_Middleware-2f-sensors-2f-imx335:
	-$(RM) ./Lib/Camera_Middleware/sensors/imx335/imx335.cyclo ./Lib/Camera_Middleware/sensors/imx335/imx335.d ./Lib/Camera_Middleware/sensors/imx335/imx335.o ./Lib/Camera_Middleware/sensors/imx335/imx335.su ./Lib/Camera_Middleware/sensors/imx335/imx335_reg.cyclo ./Lib/Camera_Middleware/sensors/imx335/imx335_reg.d ./Lib/Camera_Middleware/sensors/imx335/imx335_reg.o ./Lib/Camera_Middleware/sensors/imx335/imx335_reg.su

.PHONY: clean-Lib-2f-Camera_Middleware-2f-sensors-2f-imx335

